=begin
#Merge Ticketing API

#The unified API for building rich integrations with multiple Ticketing platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeTicketingClient::CategoryEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeTicketingClient::CategoryEnum do
  let(:instance) { MergeTicketingClient::CategoryEnum.new }

  describe 'test an instance of CategoryEnum' do
    it 'should create an instance of CategoryEnum' do
      expect(instance).to be_instance_of(MergeTicketingClient::CategoryEnum)
    end
  end
end
