=begin
#Merge Ticketing API

#The unified API for building rich integrations with multiple Ticketing platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeTicketingClient::CommentEndpointRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeTicketingClient::CommentEndpointRequest do
  let(:instance) { MergeTicketingClient::CommentEndpointRequest.new }

  describe 'test an instance of CommentEndpointRequest' do
    it 'should create an instance of CommentEndpointRequest' do
      expect(instance).to be_instance_of(MergeTicketingClient::CommentEndpointRequest)
    end
  end
  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
