=begin
#Merge Ticketing API

#The unified API for building rich integrations with multiple Ticketing platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeTicketingClient::MethodEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeTicketingClient::MethodEnum do
  let(:instance) { MergeTicketingClient::MethodEnum.new }

  describe 'test an instance of MethodEnum' do
    it 'should create an instance of MethodEnum' do
      expect(instance).to be_instance_of(MergeTicketingClient::MethodEnum)
    end
  end
end
